### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by azu** [azu/test-checklist#1]
- [ ] [はじめに](https://jsprimer.net/intro/)
- [ ] [著者紹介](https://jsprimer.net/intro/authors/)
- [ ] [読み始める前の事前準備](https://jsprimer.net/intro/preparation/)
- [ ] [文章の間違いに気づいたら](https://jsprimer.net/intro/feedback/)
- [ ] [第一部: 基本文法](https://jsprimer.net/basic/)
- [ ] [JavaScriptとは](https://jsprimer.net/basic/introduction/)
- [ ] [コメント](https://jsprimer.net/basic/comments/)
- [ ] [変数と宣言](https://jsprimer.net/basic/variables/)
- [ ] [値の評価と表示](https://jsprimer.net/basic/read-eval-print/)
- [ ] [データ型とリテラル](https://jsprimer.net/basic/data-type/)
- [ ] [演算子](https://jsprimer.net/basic/operator/)
- [ ] [暗黙的な型変換](https://jsprimer.net/basic/implicit-coercion/)
- [ ] [関数と宣言](https://jsprimer.net/basic/function-declaration/)
- [ ] [文と式](https://jsprimer.net/basic/statement-expression/)
- [ ] [条件分岐](https://jsprimer.net/basic/condition/)
- [ ] [ループと反復処理](https://jsprimer.net/basic/loop/)
- [ ] [オブジェクト](https://jsprimer.net/basic/object/)
- [ ] [プロトタイプオブジェクト](https://jsprimer.net/basic/prototype-object/)
- [ ] [配列](https://jsprimer.net/basic/array/)
- [ ] [文字列](https://jsprimer.net/basic/string/)
- [ ] [文字列とUnicode](https://jsprimer.net/basic/string-unicode/)
- [ ] [ラッパーオブジェクト](https://jsprimer.net/basic/wrapper-object/)
- [x] #2
- [ ] [関数とthis](https://jsprimer.net/basic/function-this/)
- [x] #3
- [x] #4
- [x] #5
- [ ] [Map/Set](https://jsprimer.net/basic/map-and-set/)
- [ ] [JSON](https://jsprimer.net/basic/json/)
- [ ] [Date](https://jsprimer.net/basic/date/)
- [ ] [Math](https://jsprimer.net/basic/math/)
- [ ] [ECMAScriptモジュール](https://jsprimer.net/basic/module/)
- [ ] [ECMAScript](https://jsprimer.net/basic/ecmascript/)
- [ ] [第一部: おわりに](https://jsprimer.net/basic/other-parts/)
- [ ] [第二部: 応用編（ユースケース）](https://jsprimer.net/use-case/)
- [ ] [アプリケーション開発の準備](https://jsprimer.net/use-case/setup-local-env/)
- [ ] [Ajax通信](https://jsprimer.net/use-case/ajaxapp/)
- [ ] [エントリーポイント](https://jsprimer.net/use-case/ajaxapp/entrypoint/)
- [ ] [HTTP通信](https://jsprimer.net/use-case/ajaxapp/http/)
- [ ] [データを表示する](https://jsprimer.net/use-case/ajaxapp/display/)
- [ ] [Promiseを活用する](https://jsprimer.net/use-case/ajaxapp/promise/)
- [ ] [Node.jsでCLIアプリ](https://jsprimer.net/use-case/nodecli/)
- [ ] [Node.jsでHello World](https://jsprimer.net/use-case/nodecli/helloworld/)
- [ ] [コマンドライン引数を処理する](https://jsprimer.net/use-case/nodecli/argument-parse/)
- [ ] [ファイルを読み込む](https://jsprimer.net/use-case/nodecli/read-file/)
- [ ] [MarkdownをHTMLに変換する](https://jsprimer.net/use-case/nodecli/md-to-html/)
- [ ] [ユニットテストを記述する](https://jsprimer.net/use-case/nodecli/refactor-and-unittest/)
- [ ] [Todoアプリ](https://jsprimer.net/use-case/todoapp/)
- [ ] [エントリーポイント](https://jsprimer.net/use-case/todoapp/entrypoint/)
- [ ] [アプリの構成要素](https://jsprimer.net/use-case/todoapp/app-structure/)
- [ ] [Todoアイテムの追加を実装する](https://jsprimer.net/use-case/todoapp/form-event/)
- [ ] [イベントとモデル](https://jsprimer.net/use-case/todoapp/event-model/)
- [ ] [Todoアイテムの更新と削除を実装する](https://jsprimer.net/use-case/todoapp/update-delete/)
- [ ] [Todoアプリのリファクタリング](https://jsprimer.net/use-case/todoapp/final/)
- [ ] [付録: 参考リンク集](https://jsprimer.net/appendix/links/)
- [ ] [付録: JavaScriptチートシート](https://jsprimer.net/cheatsheet/)
- [ ] [おわりに](https://jsprimer.net/outro/)
